name: Build PDF Splitter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build with PyInstaller
      shell: cmd
      run: |
        python -m PyInstaller --clean --onefile --noconsole --name "PDF分割工具" --add-data "README.md;." pdf_splitter_tkinter_new.py
        dir dist
        echo "Build directory contents:"
        dir /s /b dist

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: PDF分割工具
        path: dist/PDF分割工具.exe

    - name: Create Release Tag
      id: tag
      run: |
        echo "::set-output name=tag_name::v${{ github.run_number }}"
        echo "::set-output name=release_name::Release v${{ github.run_number }}"

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/PDF分割工具.exe"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.tag.outputs.tag_name }}
        name: ${{ steps.tag.outputs.release_name }}
        draft: false
        prerelease: false
        allowUpdates: true
        replacesArtifacts: true 