name: Build PDF Splitter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        echo "Python and pip versions:"
        python --version
        pip --version
        
    - name: Build with PyInstaller
      shell: cmd
      run: |
        echo "Starting PyInstaller build..."
        python -m PyInstaller --clean --onefile --noconsole --name "PDFSplitter" pdf_splitter_tkinter_new.py
        echo "PyInstaller finished. Checking dist directory content:"
        dir dist
        echo "Full path check:"
        dir /s /b dist\*.exe

    - name: DEBUG - Verify executable exists
      shell: cmd
      run: |
        echo "Current directory:"
        cd
        echo "Directory contents:"
        dir
        echo "DIST directory contents:"
        dir dist
        if exist "dist\PDFSplitter.exe" (
          echo "SUCCESS: PDFSplitter.exe exists!"
          copy "dist\PDFSplitter.exe" "PDFSplitter.exe"
          echo "Copied to root directory"
          dir
        ) else (
          echo "ERROR: PDFSplitter.exe NOT found!"
          dir /s *.exe
        )
        
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "PDFSplitter.exe"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        allowUpdates: true
        replacesArtifacts: true 