name: Build PDF Splitter (Fresh Start)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller==6.3.0 # Explicitly install PyInstaller

      - name: Build executable
        shell: cmd
        run: |
          echo "Running PyInstaller..."
          pyinstaller --noconfirm --onefile --noconsole --name "PDFSplitter" pdf_splitter_tkinter_new.py
          echo "Build finished. Checking dist directory:"
          dir dist
          if not exist "dist\PDFSplitter.exe" (
            echo "Build failed: PDFSplitter.exe not found!"
            exit /b 1
          )
          echo "Build successful!"

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/PDFSplitter.exe"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          body: "Fresh build: v${{ github.run_number }}"
          allowUpdates: true
          replacesArtifacts: true 